version: '3'
services:
  dev:
    image: nlp-dev-cuda
    tty: true
    build:
      context: .
    volumes:
      - .:/polish-nlm
    mem_limit: ${MEM_LIMIT_ML}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT_ML}
              capabilities: [gpu]
    environment:
      - PYTHONPATH=/polish-nlm/KLEJ
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_PROJECT=${WANDB_PROJECT}